---
- name: installs yum-utils on centos
  yum:
    name: yum-utils
    state: present

- name: installs lvm2 on centos
  yum:
    name: lvm2
    state: present

- name: Add repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name : Installs container-selinux
  yum:
    name: container-selinux
    state: present
- name: Installs docker
  yum:
    name: docker-ce
    state: present
