---
- name: Copies kubernetes.repo file
  copy:
    src: ../files/kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo

- name: installs kubelet 
  yum:
    name: kubelet 
    state: present

- name: installs kubeadm
  yum:
    name: kubeadm
    state: present

- name: installs kubectl
  yum:
    name: kubectl
    state: present

- name: Unconditionally reboot the machine with all defaults
  reboot:
  notify:
    - enable docker
    - enable kubelet
    - start docker
    - start kubelet

- name: adds cgroupfs as cgroup-driver
  command: sed -i 's/cgroup-driver=systemd/cgroup-driver=cgroupfs/g' /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
  notify:
    - restart kubelet

- name: Initializing the kluster master
  command: kubeadm init

