---
# tasks file for klusterMaster
- name: prepares the system
  include_tasks: systemProvision.yml
#######################################################
- name: includes docker dependencies
  include_tasks: dockerDeps.yml


