---
- name: creates config directory
  file:
    path: "{{ user_home }}"/.kube
    state: directory

- name: copy config file
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ user_home }}"/.kube/config
    owner: "{{ user_name }}" 
    group: "{{ user_name }}"

- name: deploy the flannel network to the kubernetes cluster    
  command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
