---
- name: Disable SELinux
  selinux:
    state: disabled
- name: Load br_netfilter kernel Module  
  modprobe:
    name: br_netfilter
    state: present
  register: modprobe
- name: Load br_netfilter permanently 
  copy:
    src: ../files/br_netfilter.conf
    dest: /etc/modules-load.d/br_netfilter.conf
    owner: root
    group: root
- name: set bridge-nf-call-iptables to 1 in sysctl.conf
  sysctl: 
    name: net.bridge.bridge-nf-call-iptables 
    value: 1
    state: present
    reload: yes
- name: set bridge-nf-call-ip6tables to 1 in sysctl.conf
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: 1
    state: present
    reload: yes


