---
# handlers file for kuberMaster
- name: enable docker
  systemd:
    name: docker
    enabled: yes

- name: enable kubelet
  systemd:
    name: kubelet
    enabled: yes

- name: start docker
  systemd:
    name: docker
    state: started

- name: start kubelet
  systemd:
    name: kubelet
    state: started

- name: restart kubelet
  systemd:
    name: kubelet
    state: restarted
    daemon-reload: yes
    
  
  
